### ISSUE TITLE
Not working with Hyphenopoly_Loader

### ISSUE THREAD

**Issue by andremacola** [RelaxedJS/ReLaXed#108]
See below

```
Page error: Error: TypeError: Failed to fetch
    at fetchBinary (file:///Users/XXXXX/Web/OnyxManager/Paper/assets/js/Hyphenopoly/Hyphenopoly_Loader.js:316:24)
    at binLoader (file:///Users/XXXXX/Web/OnyxManager/Paper/assets/js/Hyphenopoly/Hyphenopoly_Loader.js:359:13)
    at loadRessources (file:///Users/XXXXX/Web/OnyxManager/Paper/assets/js/Hyphenopoly/Hyphenopoly_Loader.js:424:13)
    at doReqLangs (file:///Users/XXXXX/Web/OnyxManager/Paper/assets/js/Hyphenopoly/Hyphenopoly_Loader.js:526:17)
    at Array.forEach (<anonymous>)
    at featureTestCSSHyphenation (file:///Users/XXXXX/Web/OnyxManager/Paper/assets/js/Hyphenopoly/Hyphenopoly_Loader.js:522:32)
    at H9YL (file:///Users/XXXXX/Web/OnyxManager/Paper/assets/js/Hyphenopoly/Hyphenopoly_Loader.js:552:6)
    at file:///Users/XXXXX/Web/OnyxManager/Paper/assets/js/Hyphenopoly/Hyphenopoly_Loader.js:586:2
Page error: Error: TypeError: Failed to fetch
    at fetchBinary (file:///Users/XXXXX/Web/OnyxManager/Paper/assets/js/Hyphenopoly/Hyphenopoly_Loader.js:316:24)
    at binLoader (file:///Users/XXXXX/Web/OnyxManager/Paper/assets/js/Hyphenopoly/Hyphenopoly_Loader.js:359:13)
    at loadRessources (file:///Users/XXXXX/Web/OnyxManager/Paper/assets/js/Hyphenopoly/Hyphenopoly_Loader.js:432:9)
    at doReqLangs (file:///Users/XXXXX/Web/OnyxManager/Paper/assets/js/Hyphenopoly/Hyphenopoly_Loader.js:526:17)
    at Array.forEach (<anonymous>)
    at featureTestCSSHyphenation (file:///Users/XXXXX/Web/OnyxManager/Paper/assets/js/Hyphenopoly/Hyphenopoly_Loader.js:522:32)
    at H9YL (file:///Users/XXXXX/Web/OnyxManager/Paper/assets/js/Hyphenopoly/Hyphenopoly_Loader.js:552:6)
    at file:///Users/XXXXX/Web/OnyxManager/Paper/assets/js/Hyphenopoly/Hyphenopoly_Loader.js:586:2
```

**Comment by Zulko** [comment]
You should share your code so we see how you are importing it.

**Comment by andremacola** [comment]
```
script.
	var word = "FORCEHYPHENOPOLY";
	var Hyphenopoly = {
		require: {
			"pt": word
		},
		paths: {
			patterndir: "assets/js/Hyphenopoly/patterns/",
			maindir: "assets/js/Hyphenopoly/"
		},
		setup: {
			classnames: {
				"post-content": {}
			}
		}
	};
script(src="assets/js/Hyphenopoly/Hyphenopoly_Loader.js")
```

Maybe because `Hyphenopoly_Loader` is loading another bunch of JS based on browser?

**Comment by Zulko** [comment]
It could be this. Chrome prevents JS scripts to load files from your computer (which is great), the solution would be to load an online version of the framework, that will work. Maybe try linking directly to the github file ? (you may need [rawgit](https://rawgit.com/))
