### ISSUE TITLE
Error in creation

### ISSUE THREAD

**Issue by AndiLeni** [RelaxedJS/ReLaXed#120]
I get the following error:

````
(node:2324) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.printToPDF): Invalid parameters displayHeaderFooter: boolean value expected
    at Promise (C:\Users\andil\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\puppeteer\lib\Connection.js:186:56)
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\andil\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\puppeteer\lib\Connection.js:185:12)
    at Page.pdf (C:\Users\andil\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\puppeteer\lib\Page.js:911:39)
    at Page.<anonymous> (C:\Users\andil\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\puppeteer\lib\helper.js:145:23)
    at exports.masterToPDF (C:\Users\andil\AppData\Roaming\npm\node_modules\relaxedjs\src\masterToPDF.js:140:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

**Comment by Zulko** [comment]
looks like something that was fixed on github but i didnt update the npm version. Give me a few moments...

**Comment by Zulko** [comment]
I pushed the latest version on npm. Could you try reinstalling and tell us if it is fixed ?

**Comment by AndiLeni** [comment]
I'm running an update to Node 10.
When it's ready, i'll give you an update.

**Comment by AndiLeni** [comment]
The update works fine. There aren't any more errors.
