### ISSUE TITLE
--no-sandbox does not work

### ISSUE THREAD

**Issue by ifgeny87** [RelaxedJS/ReLaXed#127]
When i run

`./node_modules/.bin/relaxed temp/my.pug --build-once`

then I can see these logs

```
--- puppeteerConfig= { headless: true,
  args:
   [ '--no-sandbox',
     '--disable-translate',
     '--disable-extensions',
     '--disable-sync' ] }
```

In another case when I run next line

`./node_modules/.bin/relaxed temp/my.pug --no-sandbox --build-once`

then I can see next logs

```
--- puppeteerConfig= { headless: true,
  args:
   [ '--disable-translate',
     '--disable-extensions',
     '--disable-sync' ] }
```

Fix it please

**Comment by ifgeny87** [comment]
I'm sure problem in here

```
// Google Chrome headless configuration
const puppeteerConfig = {
  headless: true,
  args: (program.sandbox ? ['--no-sandbox'] : []).concat([
    '--disable-translate',
    '--disable-extensions',
    '--disable-sync'
  ])
}
```

**Comment by DanielRuf** [comment]
Hi,

please provide more info about your environment (`node --version` and the version of relaxed).

**Comment by DanielRuf** [comment]
Should be probably `!program.sandbox ? ['--no-sandbox'] : []` as this was the case before.
I will provide a PR.

**Comment by ifgeny87** [comment]
Hi,

```
node -v
v11.14.0
```

My problem started when I trying to use relaxed as pdf-bot in docker container.
Below is one of my try:

```
root@77c3a877cee7:/opt/app# /opt/app/node_modules/.bin/relaxed --no-sandbox temp/my.pug --build-once --no-sandbox
Launching ReLaXed...
(node:1807) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
[0423/134407.250196:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/opt/app/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/opt/app/node_modules/puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:198:15)
    at Interface.close (readline.js:395:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1142:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
(node:1807) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1807) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by DanielRuf** [comment]
Broken since https://github.com/RelaxedJS/ReLaXed/commit/d4b2b29503b552a4ad646c714fc92af06e4b603b

**Comment by DanielRuf** [comment]
The provided PR should fix this.
