### ISSUE TITLE
I cannot use relaxed in docker container

### ISSUE THREAD

**Issue by hetianyi** [RelaxedJS/ReLaXed#138]
Base docker image: ```minidocks/chromium```

```relaxed --bo  --no-sandbox 123.html```

Output is:
```
Launching ReLaXed...

Processing 123.html...
... HTML generated in 0.0s
... Document loaded in 0.1s
... Network idled in 0.2s
(node:341) UnhandledPromiseRejectionWarning: Error: Protocol error (IO.read): Invalid parameters handle: string value expected
    at Promise (/usr/lib/node_modules/relaxedjs/node_modules/_puppeteer@1.18.1@puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/usr/lib/node_modules/relaxedjs/node_modules/_puppeteer@1.18.1@puppeteer/lib/Connection.js:182:12)
    at Function.readProtocolStream (/usr/lib/node_modules/relaxedjs/node_modules/_puppeteer@1.18.1@puppeteer/lib/helper.js:238:37)
  -- ASYNC --
    at Page.<anonymous> (/usr/lib/node_modules/relaxedjs/node_modules/_puppeteer@1.18.1@puppeteer/lib/helper.js:111:15)
    at exports.masterToPDF (/usr/lib/node_modules/relaxedjs/src/masterToPDF.js:153:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:341) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:341) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```node v10.14.2```
```npm 6.4.1```

The result PDF is empty! Can anybody tell me why?

**Comment by DanielRuf** [comment]
Hi @hetianyi,

Did you already check the Google search results for "Error: Protocol error (IO.read): Invalid parameters"? It seems it is an issue related to Puppeteer and some OS.

**Comment by DanielRuf** [comment]
See

https://github.com/GoogleChrome/puppeteer/issues/4637

https://github.com/GoogleChrome/puppeteer/pull/4587

https://github.com/GoogleChrome/puppeteer/issues/4609

You can try to downgrade puppeteer.

**Comment by hetianyi** [comment]
Thanks, I downgraded the Puppeteer from 1.8.1 to 1.7.0 and solved the problem.
I did this by modifying the packaged.json of relaxedjs and re-executing `npm i`.
I hope this will help others.
