### ISSUE TITLE
ReLaXed doesn't work on WSL

### ISSUE THREAD

**Issue by vegansk** [RelaxedJS/ReLaXed#146]
Process fails on Windows Subsystem for Linux with message:

```
  r8: 0000000000000000  r9: 00007fffe61bc270 r10: 0000000000000008 r11: 0000000000000008
 r12: 00007fffe61bd538 r13: 00007fffe61bc518 r14: 00007fffe61bc518 r15: 00007fffe61bc530
  di: 0000000000000002  si: 00007fffe61bc270  bp: 00007fffe61bc4c0  bx: 00007f1ed8e0c840
  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000008  sp: 00007fffe61bc270
  ip: 00007f1ed8a5ee97 efl: 0000000000000246 cgf: 00000053002b0033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/mnt/d/work/oss/wiki/mind-db/doc-examples/test-relaxedjs/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.<anonymous> (/mnt/d/work/oss/wiki/mind-db/doc-examples/test-relaxedjs/node_modules/puppeteer/lib/Launcher.js:337:50)      at Interface.emit (events.js:215:7)
    at Interface.close (readline.js:403:8)
    at Socket.onend (readline.js:180:10)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1198:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:1476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 10.37s.
```

**Comment by Zulko** [comment]
Maybe it's more a Pupetteer issue?

**Comment by vegansk** [comment]
Found [this](https://github.com/puppeteer/puppeteer/issues/1837#issuecomment-545551412)

**Comment by DanielRuf** [comment]
Hi @vegansk,

Thanks for the link. Can you confirm that this solves your problem by changing the relevant lines in ReLaXed?

**Comment by vegansk** [comment]
Hi @DanielRuf . Yes, adding flags `'--no-sandbox', '--disable-setuid-sandbox'` to puppeteer arguments fixes the problem.

Adding --no-sandbox to relaxed parameters fixes it too.  Closing the issue

**Comment by DanielRuf** [comment]
Do we have to document this?
