### ISSUE TITLE
launch relaxed without arguments results in TypeError

### ISSUE THREAD

**Issue by ingorichter** [RelaxedJS/ReLaXed#18]
Lauched `relaxed` on command line to see the options. I was greeted with a TypeError because input was `undefined`

``` 
output = input.substr(0, input.lastIndexOf('.')) + '.pdf'
                 ^

TypeError: Cannot read property 'substr' of undefined
    at Object.<anonymous> (/Users/irichter/develop/fun/OSS/ReLaXed/src/index.js:24:18)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

**Comment by Zulko** [comment]
fixed by PR #23
