### ISSUE TITLE
Error: Failed to launch the browser process

### ISSUE THREAD

**Issue by koslambrou** [RelaxedJS/ReLaXed#201]
I use NixOS. As `relaxed` is not packaged in `nixpkgs`, I attempted to install it using `npx` with:

```
npx --package=relaxedjs
```

That part works. However, when I tried running `relaxed document.pug`, I got the following error:

```
Launching ReLaXed...
/home/xxx/.npm/_npx/fe93568e581428cd/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241
            reject(new Error([
                   ^

Error: Failed to launch the browser process! spawn /home/xxx/.npm/_npx/fe93568e581428cd/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/xxx/.npm/_npx/fe93568e581428cd/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at ChildProcess.<anonymous> (/home/xxx/.npm/_npx/fe93568e581428cd/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:233:85)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.18.2
```

**Comment by Flakebi** [comment]
You can set `PUPPETEER_EXECUTABLE_PATH` to chromium to make it work.
I didn’t run it recently but this package worked some time ago: https://github.com/Flakebi/nixpkgs/commit/84496290b77ab0403601b4b82ad582123017e784

**Comment by koslambrou** [comment]
Awesome, your Nix config works. Any plans for adding it to nixpkgs?

**Comment by Flakebi** [comment]
Nice :)
I have on plans to add it myself (not using it much anymore and want to try out typst next). But feel free to take my commit and add it yourself if you want.
