### ISSUE TITLE
Install help

### ISSUE THREAD

**Issue by SeaDude** [RelaxedJS/ReLaXed#51]
Hello, 

Not sure whats up here. Updated `npm` then installed like so. Getting errors I know not how to debug.
```
user5@system5:~$ sudo npm i -g relaxedjs

/usr/bin/relaxed -> /usr/lib/node_modules/relaxedjs/src/index.js

> node-sass@4.9.0 install /usr/lib/node_modules/relaxedjs/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/lib/node_modules/relaxedjs/node_modules/node-sass/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/relaxedjs/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/usr/lib/node_modules/relaxedjs/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/lib/node_modules/relaxedjs/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/usr/lib/node_modules/relaxedjs/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/usr/lib/node_modules/relaxedjs/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib/node_modules/relaxedjs/node_modules/node-sass/vendor' }

> puppeteer@1.4.0 install /usr/lib/node_modules/relaxedjs/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r555668! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/relaxedjs/node_modules/puppeteer/.local-chromium'
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib/node_modules/relaxedjs/node_modules/puppeteer/.local-chromium' }
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/relaxedjs/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.4.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user5/.npm/_logs/2018-05-12T22_56_21_818Z-debug.log
```

**Comment by Zulko** [comment]
Try without sudo, and if it doesnt work try a local install - see the troubleshooting section of the wiki.

**Comment by SeaDude** [comment]
The local installation worked. Thank you.

**Comment by Zulko** [comment]
For the record ehat is your OS ?

**Comment by DanielRuf** [comment]
Try to disable your antivirus (realtime protection) and never use sudo for npm.

**Comment by SeaDude** [comment]
I"m on Ubuntu 16.04 LTS.

**Comment by Zulko** [comment]
Thanks, i am also on ubuntu and i am unable to install globally. Would you mind changing the issue name to: unable to install globally on ubuntu. 

If more people have the issue ill add anote directly in the readme

**Comment by DanielRuf** [comment]
> Thanks, i am also on ubuntu and i am unable to install globally. Would you mind changing the issue name to: unable to install globally on ubuntu.

We can easily test this on Travis CI as they also use Ubuntu by default.
I guess it is just an issue how Node.js and npm were installed.

**Comment by SeaDude** [comment]
If it helps at all, I went back through my archives... I originally installed `npm` by installing `nodeJS`. (npm in part of the nodeJS install) using the instructions[ found here](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions).
