### ISSUE TITLE
Error on Windwos npm installation

### ISSUE THREAD

**Issue by kwoxer** [RelaxedJS/ReLaXed#60]
Hey, great project first of all. But installing on a Windows system with Node.js v 8.11.2 I get an error when I want to compile relaxed document.

`relaxed my_document.pug
Launching ReLaXed...

Now waiting for changes in my_document.pug and its directory
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: watch C:\Users\kwoxer\Anwendungsdaten EPERM
    at _errnoException (util.js:992:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\chokidar\lib\nodefs-handler.js:37:15)
    at setFsWatchListener (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\chokidar\lib\nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\chokidar\lib\nodefs-handler.js:229:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\chokidar\lib\nodefs-handler.js:408:19)
    at FSWatcher.<anonymous> (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\chokidar\lib\nodefs-handler.js:456:19)
    at FSWatcher.<anonymous> (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\chokidar\lib\nodefs-handler.js:461:16)
    at FSReqWrap.oncomplete (fs.js:153:5)`

How can I fix it? Is it because of the old Node.js Version?

**Comment by DanielRuf** [comment]
Permission issue. Do you have any antivirus solution active or did you run the command as admin / non-admin?

**Comment by Zulko** [comment]
May be a permission issue, but could you also try with the latest versions of Node and ReLaXed, just to be sure that's not just a version problem ?

**Comment by kwoxer** [comment]
Strange. I started cmd.exe with admin. But same error output.

Then tried with powershell. Now I get 
`+ relaxed my_document.pug
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (relaxed:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
`

In which folder do I need to start
**relaxed my_document.pug** ?

I installed relaxed globally btw. Thanks.

**Comment by kwoxer** [comment]
Ok now I installed Node.js Version 10. Now the output looks better

`C:\Users\kwoxer>relaxed my_document.pug
C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\node-sass\lib\binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\node-sass\vendor\win32-x64-64\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 10.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\src\converters.js:12:14)`

**Comment by Zulko** [comment]
it tells you that you need to NPM install again

**Comment by DanielRuf** [comment]
> it tells you that you need to NPM-install ReLaXed again.

It is just `node-sass`. He has to install `windows-build-tools` globally and then run `npm rebuild node-sass --force`.

**Comment by DanielRuf** [comment]
> This usually happens because your environment has changed since running `npm install`.
> Run `npm rebuild node-sass --force` to build the binding for your current environment.

This is expected as your Node.js version has changed and the binary was built with Node.js 8. Either delete `node_modules` and run `npm i` again or just rebuild `node-sass`.

**Comment by kwoxer** [comment]
I tried the followings:
- npm rebuild node-sass --force
- npm i npm

But did not help. Also did:
- npm install -g --production windows-build-tools

that run 5 min.

Than again run npm rebuild node-sass --force. But still same issue. I'm out of ideas.

**Comment by kwoxer** [comment]
Somehow it has issues to rebuild node-sass.

So I deleted that folder. For me it was 
- C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs

Now installed again for node v10:
- npm i -g relaxedjs

But when I do relaxed my_document.pug now, I still get no real success, but it's step in the right way:
```
C:\WINDOWS\system32>relaxed my_document.pug
Launching ReLaXed...

Now waiting for changes in my_document.pug and its directory
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, watch 'C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5'
    at FSWatcher.start (fs.js:1389:26)
    at Object.fs.watch (fs.js:1426:11)
    at createFsWatchInstance (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\chokidar\lib\nodefs-handler.js:37:15)
    at setFsWatchListener (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\chokidar\lib\nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\chokidar\lib\nodefs-handler.js:229:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\chokidar\lib\nodefs-handler.js:408:19)
    at FSWatcher.<anonymous> (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\chokidar\lib\nodefs-handler.js:456:19)
    at FSWatcher.<anonymous> (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\chokidar\lib\nodefs-handler.js:461:16)
    at FSReqWrap.oncomplete (fs.js:166:5)
Emitted 'error' event at:
    at FSWatcher._handleError (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\chokidar\index.js:260:10)
    at createFsWatchInstance (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\chokidar\lib\nodefs-handler.js:39:5)
    at setFsWatchListener (C:\Users\kwoxer\AppData\Roaming\npm\node_modules\relaxedjs\node_modules\chokidar\lib\nodefs-handler.js:80:15)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:166:5)
```

**Comment by DanielRuf** [comment]
Then just delete package-lock.json (if it was generated) + node_modules and try a fresh `npm i`.

Normally there should be some debug infos on the console why it did not work.

In this case please post the full output.

**Comment by DanielRuf** [comment]
> Somehow it has issues to rebuild node-sass

Did you restart your system afterwards and did you make sure that all needed things from the build tools (python 2) is available in your environment (in your `PATH`).

**Comment by DanielRuf** [comment]
There is some issue with the temp / cache folder in your setup. Make sure that all browsers are closed and not running in the background and that no antivirus solution interferes.

An elevated prompt may be also helpful.

Personally I never head this issue so I can just give some probably helpful ideas.

**Comment by DanielRuf** [comment]
Wait, why do you run the command in a Windows system folder? Please try running it in your desktopr or any other normal user folder.

**Comment by DanielRuf** [comment]
Because the watcher (chokidar) tries to access these and should not have any access to system files so you get the error (which is good).

**Comment by kwoxer** [comment]
Well, you are right, on the system folder, the issue still persist.

But when I run it on my Desktop, I get this one:

```
C:\Users\kwoxer\Desktop>relaxed my_document.pug
Launching ReLaXed...

Now waiting for changes in my_document.pug and its directory
```

but it does not fail or so. It just stays with this output.

**Comment by Zulko** [comment]
As it says, it is waiting for changes in the directory to generate the output. This is the expected behaviour.

**Comment by DanielRuf** [comment]
The system directories should never be directly used.

Try `relaxed my_document.pug --build-once` on your desktop or elsewhere. This was added in the latest release (1.4.0)?

**Comment by kwoxer** [comment]
Now it works when I download the needed files and running it in a folder on my Desktop. Thank you guys you helped me a lot.
