### ISSUE TITLE
chart.js not not render

### ISSUE THREAD

**Issue by jaroslawziolkowski** [RelaxedJS/ReLaXed#75]
Hello,
I have installed ReLaXed on Mac Os and Debian 9. nodeJS version 8.11.2
a directory structure is
ep.pug
styles.scss
diagrams
 pie.chart.js

in chart.js is 

```
{
  type: 'pie',
  data: {
    datasets: [{
      data: [10, 20, 30],
      backgroundColor:["#db7575", "#dbc575", "#75b0db"]
    }],
    labels: ['Normal', 'Osteopenia', 'Osteoporosis']
  },
  options: {
    width:500,
    height:500,
    devicePixelRatio: 3,
    legend: {
      position: 'bottom'
    }
  }
};

```

compilation works well no errors, pdf is creating but an image from chart.js no. Any suggests?

**Comment by Zulko** [comment]
When relaxed is watching, and you modify the .chart.js file, a png file should be generated. Does that gappen or is there an error ?

Which version of relaxed do you use, is it the latest version (from circa 3h ago) ? There may be some fixes in thay version.

**Comment by jaroslawziolkowski** [comment]
Error what is in my console

> UnhandledPromiseRejectionWarning: TypeError: page.waitForfunction is not a function
>     at Object.exports.chartjsToPNG (node_modules/relaxedjs/src/converters.js:215:14)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
> (node:2906) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:2906) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


I use version 0.1.6

BTW for --build once also it should be created?

**Comment by Zulko** [comment]
This looks like a typo that was introduced in the latest version(s) :(
That feature is not covered by the tests yet, I cant patch it now, but certainly in at some point in the next 24h.

Regarding your last question, build-once does not render files like ".chart.json", these files must be rendered to PNG before you run build once, and can only be rendered in "watch" mode. There is no easy way to build these automatically with build-once at the moment, but we could in the future have a feature like

```
relaxed pie.chart.js
```

To build the plot alone.

**Comment by jaroslawziolkowski** [comment]
Any update on this issue?
