### ISSUE TITLE
When I run relaxed my_document.pug on windows I get this

### ISSUE THREAD

**Issue by robbertstevens** [RelaxedJS/ReLaXed#78]
```
async function main () {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

Windows 10 using git bash. I get the same when I just run relaxed

**Comment by DanielRuf** [comment]
Please upgrade Node.js to at least 8 or 10.

**Comment by DanielRuf** [comment]
`async` is a new keyword and not available in older Node.js versions.

**Comment by robbertstevens** [comment]
it works now, thank!
