### ISSUE TITLE
Error when starting ReLaXed

### ISSUE THREAD

**Issue by Calinou** [RelaxedJS/ReLaXed#81]
**OS:** Fedora 27
**Node.js version:** 8.11.2

When running `relaxed example_file.pug`, I get:

```
(node:15547) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:15547) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15547) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I installed ReLaXed using `yarn global add relaxedjs`.

**Comment by DanielRuf** [comment]
Do you have some firewall or security solution running which blocks the browser from starting?

**Comment by Calinou** [comment]
@DanielRuf No, both SELinux and firewalld are disabled on my machine.

**Comment by DanielRuf** [comment]
> However, I only have Chromium (and not Google Chrome) installed. A few weeks ago, I've been able to get ReLaXed working on a different machine with the same OS though.

Interesting, can this be reproduced?

**Comment by Zulko** [comment]
Any success with this @Calinou ?
