### ISSUE TITLE
Cannot find module 'perf_hooks'

### ISSUE THREAD

**Issue by nbeeee** [RelaxedJS/ReLaXed#95]
relaxed my_document.pug

Error: Cannot find module 'perf_hooks'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\relaxedjs\src\index.js:8:25)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

**Comment by DanielRuf** [comment]
Please provide more infos about your environment (Node.js version, OS and OS version) and the steps that you took.

**Comment by Zulko** [comment]
According to #33 it could just be an outdated Node version, at which case updating npm and/or Node (with ``npm i -g node``) could fix it.

**Comment by nbeeee** [comment]
It's really caused by the node version

**Comment by Zulko** [comment]
@nbeeee Is your problem solved by upgrading Node ?

**Comment by parthi22** [comment]
> According to #33 it could just be an outdated Node version, at which case updating npm and/or Node (with `npm i -g node`) could fix it.

faced the same issue, worked after updating the node. thanks

**Comment by Jaesung-Jun** [comment]
I fixed this problem by delete auto-generated code by ESLINT which is
```
import { callExpressionAffectsControlFlow } from 'tsutils';  
```
In my case, It caused by **callExpressionAffectsControlFlow from tsutils** but I guess it can causes from other classes from tsutils(or the other utils relate to typescripts). 

Check about this.
